apiVersion: v1
kind: ConfigMap
metadata:
    name: config-go-streaming-api
    namespace: sse-streaming
    labels:
        name: config-go-streaming-api
data:
    config: |-
        {
            "port": "80",
            "redis": {
                "host": "redis-streaming-market-service.default",
                "port": "6379",
                "db": 1,
                "password": "7e49302b475067e7177aef16f015d753"
            },
            "prefix_channel": "v1:streaming"
        }


