apiVersion: v1
kind: ConfigMap
metadata:
    name: config-go-streaming-api
    namespace: proto-actor-sample
    labels:
        name: config-go-streaming-api
data:
    config: |-
        {
            "port": "80",
            "redis": {
                "host": "redis-pubsub-streaming-service.default",
                "port": "6379",
                "db": 0,
                "password": "7e49302b475067e7177aef16f015d753"
            },
            "prefix_channel": "",
            "check_jwt": false
        }
